import {
  DashboardOutlined,
  BookOutlined,
  ExperimentOutlined,
  ShopOutlined,
  CoffeeOutlined,
  StarOutlined,
  WarningOutlined,
  AlertOutlined,
} from '@ant-design/icons';
import type { AppMenuItem } from './types';

export const MENU_ITEMS: AppMenuItem[] = [
  {
    key: 'dashboard',
    label: '仪表盘',
    icon: <DashboardOutlined />,
    roles: ['logistics', 'teacher', 'parent', 'regulator'],
    path: '/dashboard',
  },
  {
    key: 'recipes',
    label: '菜谱管理',
    icon: <BookOutlined />,
    roles: ['logistics'],
    path: '/recipes',
  },
  {
    key: 'recipes-view',
    label: '菜谱查看',
    icon: <BookOutlined />,
    roles: ['teacher', 'parent', 'regulator'],
    path: '/recipes',
  },
  {
    key: 'samples',
    label: '留样管理',
    icon: <ExperimentOutlined />,
    roles: ['logistics'],
    path: '/samples',
  },
  {
    key: 'samples-view',
    label: '留样查看',
    icon: <ExperimentOutlined />,
    roles: ['teacher', 'parent', 'regulator'],
    path: '/samples',
  },
  {
    key: 'suppliers',
    label: '供应商管理',
    icon: <ShopOutlined />,
    roles: ['logistics', 'regulator'],
    path: '/suppliers',
  },
  {
    key: 'classroom-meals-teacher',
    label: '班级用餐登记',
    icon: <CoffeeOutlined />,
    roles: ['teacher'],
    path: '/classroom-meals',
  },
  {
    key: 'classroom-meals-logistics',
    label: '班级用餐',
    icon: <CoffeeOutlined />,
    roles: ['logistics'],
    path: '/classroom-meals',
  },
  {
    key: 'classroom-meals-view',
    label: '班级用餐查看',
    icon: <CoffeeOutlined />,
    roles: ['regulator'],
    path: '/classroom-meals',
  },
  {
    key: 'escort-reviews-parent',
    label: '陪餐评价',
    icon: <StarOutlined />,
    roles: ['parent'],
    path: '/escort-reviews',
  },
  {
    key: 'escort-reviews-logistics',
    label: '陪餐评价',
    icon: <StarOutlined />,
    roles: ['logistics'],
    path: '/escort-reviews',
  },
  {
    key: 'escort-reviews-view',
    label: '陪餐评价查看',
    icon: <StarOutlined />,
    roles: ['teacher', 'regulator'],
    path: '/escort-reviews',
  },
  {
    key: 'rectifications',
    label: '整改管理',
    icon: <WarningOutlined />,
    roles: ['logistics', 'regulator'],
    path: '/rectifications',
  },
  {
    key: 'alerts',
    label: '告警中心',
    icon: <AlertOutlined />,
    roles: ['logistics', 'regulator'],
    path: '/alerts',
  },
];
